env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
settings:
  import/resolver: webpack
rules:
  max-classes-per-file: off
  import/no-unresolved: off
  class-methods-use-this: off
  no-restricted-syntax: off
