version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NPM_GITHUB_TOKEN=$GITHUB_TOKEN
    env_file:
      - .env
    tty: true
    ports:
      - 9000:8080
    networks:
      - dynamo-local
  dynamodb-local:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./data:/data
    networks:
      - dynamo-local
networks:
  dynamo-local:
    external: true
