service:
  name: express-api

provider:
  name: aws
  runtime: 'nodejs12.x'
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  deploymentBucket: 
    name: shuji-serverless-deploy-dev
  role: 'arn:aws:iam::#{AWS::AccountId}:role/lambda-basic-role'
  timeout: 29
  memorySize: 128
  httpApi:
    authorizers:
      cognitoJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.#{AWS::Region}.amazonaws.com/ap-northeast-1_nsYbr83YQ
        audience:
          - 4s375jt92lgobq1keg4ip8r3fm
plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

functions:
  user-create:
    name: ${self:service.name}-user-create-${opt:stage}
    handler: app/http/handlers/users.create
    events:
      - http:
          path: /user/create
          method: post
          cors: true
  work-list-sync:
    name: ${self:service.name}-work-list-sync-${opt:stage}
    handler: app/http/handlers/works.workSync
    events:
      - httpApi:
          path: /work/sync
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
          async: true
custom:
  webpack:
    packager: "yarn"
    webpackConfig: ./webpack.config.js
  webpackIncludeModules: true
