service:
  name: express-api

provider:
  name: aws
  runtime: 'nodejs12.x'
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  deploymentBucket: 
    name: serverless-deploy-bucket
  role: 'arn:aws:iam::#{AWS::AccountId}:role/lambda-basic-role-${opt:stage}'
  timeout: 29
  memorySize: 128
  environment:
    SECRET_ID: zac-job-dev
  httpApi:
    authorizers:
      cognitoJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.#{AWS::Region}.amazonaws.com/ap-northeast-1_nsYbr83YQ
        audience:
          - 4s375jt92lgobq1keg4ip8r3fm    
plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

functions:
  user-create:
    name: ${self:service.name}-user-create-${opt:stage}
    handler: src/handlers/users.create
    events:
      - http:
          path: /user/create
          method: post
          cors: true
  put-zac-login:
    name: ${self:service.name}-put-zac-login-${opt:stage}
    handler: src/handlers/users.putZacLogin
    role: arn:aws:iam::#{AWS::AccountId}:role/lambda-cognito-write-role-${opt:stage}
    events:
      - http:
          path: /user/zac/login
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/ap-northeast-1_Jp6VfWMAA
  work-list-sync:
    name: ${self:service.name}-work-list-sync-${opt:stage}
    handler: src/handlers/works.workSync
    events:
      - httpApi:
          path: /work/sync
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
          async: true
  work-clock-in:
    name: ${self:service.name}-work-clock-in-${opt:stage}
    handler: src/handlers/works.clockIn
    events:
      - httpApi:
          path: /work/clock-in
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
  work-clock-out:
    name: ${self:service.name}-work-clock-out-${opt:stage}
    handler: src/handlers/works.clockOut
    events:
      - httpApi:
          path: /work/clock-out
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
  work-go-out:
    name: ${self:service.name}-work-go-out-${opt:stage}
    handler: src/handlers/works.goOut
    events:
      - httpApi:
          path: /work/go-out
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
  work-go-return:
    name: ${self:service.name}-work-go-return-${opt:stage}
    handler: src/handlers/works.goReturn
    events:
      - httpApi:
          path: /work/go-return
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer

custom:
  webpack:
    packager: "yarn"
    webpackConfig: ./webpack.config.js
  webpackIncludeModules: true
