service: ZacJobApi

provider:
  name: aws
  runtime: 'nodejs14.x'
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  deploymentBucket: 
    name: serverless-deploy-bucket
  role: 'arn:aws:iam::#{AWS::AccountId}:role/zac-job-basic-role-${opt:stage}'
  timeout: 29
  memorySize: 128
  environment:
    SECRET_ID: zac-job-dev
  httpApi:
    authorizers:
      cognitoJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.#{AWS::Region}.amazonaws.com/ap-northeast-1_nsYbr83YQ
        audience:
          - 4s375jt92lgobq1keg4ip8r3fm
plugins:
  - serverless-pseudo-parameters

functions:
  UserCreate:
    name: zac-job-api-user-create-${opt:stage}
    handler: dist/handlers/users.create
    events:
      - http:
          path: /user/create
          method: post
          cors: true
  PutZacLogin:
    name: zac-job-api-put-zac-login-${opt:stage}
    handler: dist/handlers/users.putZacLogin
    role: arn:aws:iam::#{AWS::AccountId}:role/zac-job-cognito-write-role-${opt:stage}
    events:
      - http:
          path: /user/zac/login
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/ap-northeast-1_Jp6VfWMAA
  PutObcLogin:
    name: zac-job-api-put-obc-login-${opt:stage}
    handler: dist/handlers/users.putObcLogin
    role: arn:aws:iam::#{AWS::AccountId}:role/zac-job-cognito-write-role-${opt:stage}
    events:
      - http:
          path: /user/obc/login
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/ap-northeast-1_Jp6VfWMAA
  UserZacWork:
    name: zac-job-api-user-zac-work-${opt:stage}
    handler: src/handlers/users.postZacRegister
    role: arn:aws:iam::#{AWS::AccountId}:role/zac-job-cognito-write-role-${opt:stage}
    events:
      - http:
          path: /user/zac/work
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/ap-northeast-1_Jp6VfWMAA
  WorkListSync:
    name: zac-job-api-work-list-sync-${opt:stage}
    handler: dist/handlers/works.workSync
    role: arn:aws:iam::#{AWS::AccountId}:role/zac-job-work-results-table-write-role-${opt:stage}
    events:
      - httpApi:
          path: /work/sync
          method: get
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
          async: true
  WorkList:
    name: zac-job-api-work-list-${opt:stage}
    handler: dist/handlers/works.workList
    role: arn:aws:iam::#{AWS::AccountId}:role/zac-job-work-results-table-write-role-${opt:stage}
    events:
      - httpApi:
          path: /work
          method: get
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
  WorkClockIn:
    name: zac-job-api-work-clock-in-${opt:stage}
    handler: dist/handlers/works.clockIn
    events:
      - httpApi:
          path: /work/clock-in
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
  WorkClockOut:
    name: zac-job-api-work-clock-out-${opt:stage}
    handler: dist/handlers/works.clockOut
    events:
      - httpApi:
          path: /work/clock-out
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
  WorkGoOut:
    name: zac-job-api-work-go-out-${opt:stage}
    handler: dist/handlers/works.goOut
    events:
      - httpApi:
          path: /work/go-out
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
  WorkGoReturn:
    name: zac-job-api-work-go-return-${opt:stage}
    handler: dist/handlers/works.goReturn
    events:
      - httpApi:
          path: /work/go-return
          method: post
          cors: true
          authorizer:
            name: cognitoJwtAuthorizer
